#!/usr/bin/bash

check_os() {
    if [ ! -f /etc/redhat-release ]; then
        echo "Red Hat release file not found, this is not an EPEL Linux!"
        exit 1
    fi
}

dnf_requirement() {
    if [[ $(rpm -q --quiet "$1") ]]; then
	    echo -e "[\e[92m✔\e[39m]::[$1]: is installed!";
    else
        echo -e "[\e[1m\e[91mx\e[39m]::[ERROR]: This Breed requires $1!";
        echo -e "You can install [\e[1m\e[91m$1\e[39m] using the following order as superuser:";
        echo "dnf install $1"
        exit 1
    fi
}

requirement() {
    command -v "$1" > /dev/null 2>&1
	if [ "$?" -eq "0" ]; then
	    echo -e "[\e[92m✔\e[39m]::[$1]: is installed!";
    else
        echo -e "[\e[1m\e[91mx\e[39m]::[ERROR]: This Breed requires $1!" ;
        exit 1
    fi
}

check_root() {
    if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root" 1>&2
        exit 1
    fi
}

validate_ip() {
    local ip=$1
    local stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=("$ip")
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

# 2020 - UpVent
